### ISSUE TITLE
Outside temperature wrong when under 0°C

### ISSUE THREAD

**Issue by Analogiker** [proddy/EMS-ESP-Boiler#13] opened 2018-12-18 18:53 UTC
If the outside temperature is under 0°C, then a wrong number is detected:
Console output:  Outside temperature: 6552.8 C

**Comment by proddy** [comment] 2018-12-18 19:37
good catch. I never tested for negative numbers. I checked the code it negative floats are rendered correctly so the problem is interpreting the values from the telegram. Would you mind sending me the raw data? In Verbose logging mode copy&paste a 0x19 (UBAMonitorSlow) message. Thanks

**Comment by Analogiker** [comment] 2018-12-18 19:44
Thanks for your quick reply.
-------------------------
<--- UBAMonitorSlow(0x19) received
(00:01:57) Publishing data to MQTT topics
(00:01:58) Boiler broadcast, type 0x1c len=16, data: 08 00 1c 00 00 3d b9 7b 00 00 00 00 00 00 00 74  
-------------------------
shows 0x8000 (not available ?)

**Comment by proddy** [comment] 2018-12-18 20:02
could you send the data from type 0x19? This has the outdoor temp in it.

**Comment by Analogiker** [comment] 2018-12-18 20:07
oh sorry 

(00:28:50) Boiler broadcast, type 0x19 len=32, data: 08 00 19 00 ff f3 01 6e 80 00 00 00 00 64 02 ff f1 12 bf 14 00 00 00 0c a4 5e 02 d1 ff 00 00 e8 (OK)

**Comment by proddy** [comment] 2018-12-18 20:23
ok got it. and whats the real temp outside roughly so I can double check?

**Comment by Analogiker** [comment] 2018-12-18 20:35
It's somewhat under zero °C. Depending on my position -0,5 to -0,1 
(00:57:41) Boiler broadcast, type 0x19 len=32, data: 08 00 19 00 ff f2 01 7f 80 00 00 00 00 37 02 ff f3 12 bf 20 00 00 00 0c a4 6a 02 d2 01 00 00 a8 (OK)

**Comment by proddy** [comment] 2018-12-18 20:40
is it -1.2 ?

**Comment by Analogiker** [comment] 2018-12-18 20:43
Year. That could be possible. I have no other outside thermostat.


________________________________
Von: Proddy <notifications@github.com>
Gesendet: Dienstag, Dezember 18, 2018 9:40 PM
An: proddy/EMS-ESP-Boiler
Cc: Analogiker; Author
Betreff: Re: [proddy/EMS-ESP-Boiler] Outside temperature wrong when under 0°C (#13)


is it -1.2 ?

**Comment by proddy** [comment] 2018-12-18 22:09
ok, I think I fixed it. It's hard to tell because my boiler doesn't support it. The fixed code is part of version 1.1 which I'd upload soon to github

**Comment by Analogiker** [comment] 2018-12-19 04:53
Proddy, great job. Thank you very much!! 

I wish you some nice holidays

**Comment by proddy** [comment] 2018-12-19 10:04
I'm still not certain if they use a 1's-complement or 2's-complement for representing negative values so the results may be off by 0.1. I'll leave this open so someone can double check and confirm.

**Comment by proddy** [comment] 2018-12-22 15:03
fixed in latest build.

**Closed by proddy** 2018-12-22 15:03 UTC
